on: [push]

name: Build Docker Image And Submit Metadata To Reliza Hub

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - id: setup-reliza-cli
        name: setup-reliza-cli
        uses: relizaio/setup-reliza-cli@master
      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u '${{ secrets.DOCKER_LOGIN }}' --password-stdin registry.relizahub.com
      - id: get-version
        name: Get Version
        uses: relizaio/reliza-get-version@master
        with: 
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
      - name: Instantiate Reliza status as Rejected to handle possible build failure
        run: echo "RELIZA_BUILD_STATUS=rejected" >> $GITHUB_ENV
      - name: Build and push docker container to Reliza Hub Registry
        continue-on-error: true
        run: |
          docker build -t $IMAGE_NAMESPACE/$IMAGE_NAME:${{ steps.get-version.outputs.reliza_short_version }} -t $IMAGE_NAMESPACE/$IMAGE_NAME:latest --build-arg VERSION=${{ steps.get-version.outputs.reliza_full_version }}  \
            --build-arg CI_ENV=github$GITHUB_SHA --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=$GITHUB_REF .
          docker_sha_256=$(docker push $IMAGE_NAMESPACE/$IMAGE_NAME:${{ steps.get-version.outputs.reliza_short_version }} | grep sha256 | cut -f 3 -d ' ')
          # push latest also
          docker push $IMAGE_NAMESPACE/$IMAGE_NAME:latest
          # save sha256 to env var
          echo "DOCKER_SHA_256=$docker_sha_256" >> $GITHUB_ENV
          echo "RELIZA_BUILD_STATUS=complete " >> $GITHUB_ENV
      - name: Submit metadata to Reliza Hub
        uses: relizaio/reliza-add-release@master
        with:
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          image_full_name: $IMAGE_NAMESPACE/$IMAGE_NAME
          image_digest: $DOCKER_SHA_256
          reliza_full_version: ${{ steps.get-version.outputs.reliza_full_version }}
          reliza_build_start: ${{ steps.get-version.outputs.reliza_build_start }}
          reliza_build_status: $RELIZA_BUILD_STATUS

